// ============================================================
// HSK1_DATA.JS – 150 từ vựng HSK 1 chuẩn (phiên bản cũ 6 cấp)
// Nguồn: Giáo trình HSK chuẩn quốc tế
// ============================================================

const _default_HSK1_VOCABULARY = [
  // Đại từ / Từ hỏi
  { id: 1,  hanzi: "我",     pinyin: "wǒ",       meaning: "tôi, tao",             type: "đại từ",    example: "我是学生。 - Tôi là học sinh." },
  { id: 2,  hanzi: "你",     pinyin: "nǐ",       meaning: "bạn, anh, chị",        type: "đại từ",    example: "你好！ - Xin chào!" },
  { id: 3,  hanzi: "他",     pinyin: "tā",       meaning: "anh ấy, ông ấy",       type: "đại từ",    example: "他是老师。 - Anh ấy là giáo viên." },
  { id: 4,  hanzi: "她",     pinyin: "tā",       meaning: "cô ấy, chị ấy",        type: "đại từ",    example: "她很漂亮。 - Cô ấy rất đẹp." },
  { id: 5,  hanzi: "我们",   pinyin: "wǒmen",    meaning: "chúng tôi, chúng ta",  type: "đại từ",    example: "我们是朋友。 - Chúng ta là bạn bè." },
  { id: 6,  hanzi: "你们",   pinyin: "nǐmen",    meaning: "các bạn, mọi người",   type: "đại từ",    example: "你们好吗？ - Các bạn khỏe không?" },
  { id: 7,  hanzi: "他们",   pinyin: "tāmen",    meaning: "họ (nam hoặc chung)",   type: "đại từ",    example: "他们是同学。 - Họ là bạn cùng lớp." },
  { id: 8,  hanzi: "什么",   pinyin: "shénme",   meaning: "cái gì, gì",            type: "từ hỏi",    example: "这是什么？ - Đây là cái gì?" },
  { id: 9,  hanzi: "哪",     pinyin: "nǎ",       meaning: "nào, ở đâu",            type: "từ hỏi",    example: "你是哪国人？ - Bạn là người nước nào?" },
  { id: 10, hanzi: "哪儿",   pinyin: "nǎr",      meaning: "ở đâu",                 type: "từ hỏi",    example: "你去哪儿？ - Bạn đi đâu?" },
  { id: 11, hanzi: "谁",     pinyin: "shéi",     meaning: "ai",                    type: "từ hỏi",    example: "他是谁？ - Anh ấy là ai?" },
  { id: 12, hanzi: "多少",   pinyin: "duōshao",  meaning: "bao nhiêu",             type: "từ hỏi",    example: "多少钱？ - Bao nhiêu tiền?" },
  { id: 13, hanzi: "几",     pinyin: "jǐ",       meaning: "mấy, bao nhiêu",        type: "từ hỏi",    example: "几点了？ - Mấy giờ rồi?" },
  { id: 14, hanzi: "怎么",   pinyin: "zěnme",    meaning: "thế nào, làm sao",      type: "từ hỏi",    example: "你怎么了？ - Bạn sao vậy?" },
  { id: 15, hanzi: "怎么样", pinyin: "zěnmeyàng",meaning: "thế nào, ra sao",       type: "từ hỏi",    example: "电影怎么样？ - Phim thế nào?" },

  // Số đếm
  { id: 16, hanzi: "零",  pinyin: "líng",  meaning: "số không (0)",  type: "số đếm", example: "零度。 - Không độ." },
  { id: 17, hanzi: "一",  pinyin: "yī",    meaning: "một (1)",        type: "số đếm", example: "一个苹果。 - Một quả táo." },
  { id: 18, hanzi: "二",  pinyin: "èr",    meaning: "hai (2)",         type: "số đếm", example: "二月。 - Tháng hai." },
  { id: 19, hanzi: "三",  pinyin: "sān",   meaning: "ba (3)",          type: "số đếm", example: "三个人。 - Ba người." },
  { id: 20, hanzi: "四",  pinyin: "sì",    meaning: "bốn (4)",         type: "số đếm", example: "四月。 - Tháng tư." },
  { id: 21, hanzi: "五",  pinyin: "wǔ",    meaning: "năm (5)",         type: "số đếm", example: "五十块。 - Năm mươi đồng." },
  { id: 22, hanzi: "六",  pinyin: "liù",   meaning: "sáu (6)",         type: "số đếm", example: "六点。 - Sáu giờ." },
  { id: 23, hanzi: "七",  pinyin: "qī",    meaning: "bảy (7)",         type: "số đếm", example: "七月。 - Tháng bảy." },
  { id: 24, hanzi: "八",  pinyin: "bā",    meaning: "tám (8)",         type: "số đếm", example: "八月。 - Tháng tám." },
  { id: 25, hanzi: "九",  pinyin: "jiǔ",   meaning: "chín (9)",        type: "số đếm", example: "九月。 - Tháng chín." },
  { id: 26, hanzi: "十",  pinyin: "shí",   meaning: "mười (10)",       type: "số đếm", example: "十块钱。 - Mười đồng." },
  { id: 27, hanzi: "百",  pinyin: "bǎi",   meaning: "trăm (100)",      type: "số đếm", example: "一百块。 - Một trăm đồng." },
  { id: 28, hanzi: "千",  pinyin: "qiān",  meaning: "nghìn (1000)",    type: "số đếm", example: "一千元。 - Một nghìn tệ." },
  { id: 29, hanzi: "万",  pinyin: "wàn",   meaning: "vạn (10000)",     type: "số đếm", example: "一万人。 - Một vạn người." },
  { id: 30, hanzi: "两",  pinyin: "liǎng", meaning: "hai (dùng với lượng từ)", type: "số đếm", example: "两个人。 - Hai người." },

  // Thời gian
  { id: 31, hanzi: "年",   pinyin: "nián",    meaning: "năm",            type: "thời gian", example: "今年。 - Năm nay." },
  { id: 32, hanzi: "月",   pinyin: "yuè",     meaning: "tháng",          type: "thời gian", example: "这个月。 - Tháng này." },
  { id: 33, hanzi: "日",   pinyin: "rì",      meaning: "ngày",           type: "thời gian", example: "一月一日。 - Ngày 1 tháng 1." },
  { id: 34, hanzi: "号",   pinyin: "hào",     meaning: "ngày (trong tháng)", type: "thời gian", example: "今天几号？ - Hôm nay ngày mấy?" },
  { id: 35, hanzi: "今天", pinyin: "jīntiān", meaning: "hôm nay",        type: "thời gian", example: "今天天气很好。 - Hôm nay thời tiết đẹp." },
  { id: 36, hanzi: "明天", pinyin: "míngtiān",meaning: "ngày mai",       type: "thời gian", example: "明天见！ - Hẹn gặp ngày mai!" },
  { id: 37, hanzi: "昨天", pinyin: "zuótiān", meaning: "hôm qua",        type: "thời gian", example: "昨天我很累。 - Hôm qua tôi rất mệt." },
  { id: 38, hanzi: "现在", pinyin: "xiànzài", meaning: "bây giờ, hiện tại", type: "thời gian", example: "现在几点？ - Bây giờ mấy giờ?" },
  { id: 39, hanzi: "时候", pinyin: "shíhou",  meaning: "lúc, khi",       type: "thời gian", example: "什么时候？ - Khi nào?" },
  { id: 40, hanzi: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng (trước 12h)", type: "thời gian", example: "上午九点。 - 9 giờ sáng." },
  { id: 41, hanzi: "下午", pinyin: "xiàwǔ",   meaning: "buổi chiều (13-18h)", type: "thời gian", example: "下午三点。 - 3 giờ chiều." },
  { id: 42, hanzi: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa",     type: "thời gian", example: "中午吃饭了吗？ - Bạn ăn trưa chưa?" },
  { id: 43, hanzi: "晚上", pinyin: "wǎnshang", meaning: "buổi tối",      type: "thời gian", example: "晚上好！ - Chào buổi tối!" },
  { id: 44, hanzi: "星期", pinyin: "xīngqī",  meaning: "tuần, thứ",      type: "thời gian", example: "星期一。 - Thứ hai." },
  { id: 45, hanzi: "点",   pinyin: "diǎn",    meaning: "giờ (đồng hồ)", type: "thời gian", example: "八点。 - Tám giờ." },

  // Con người & Gia đình
  { id: 46, hanzi: "人",   pinyin: "rén",    meaning: "người",          type: "danh từ", example: "中国人。 - Người Trung Quốc." },
  { id: 47, hanzi: "爸爸", pinyin: "bàba",   meaning: "bố, ba",         type: "danh từ", example: "我爸爸是医生。 - Bố tôi là bác sĩ." },
  { id: 48, hanzi: "妈妈", pinyin: "māma",   meaning: "mẹ, má",         type: "danh từ", example: "妈妈做饭。 - Mẹ nấu cơm." },
  { id: 49, hanzi: "儿子", pinyin: "érzi",   meaning: "con trai",        type: "danh từ", example: "他有一个儿子。 - Anh ấy có một con trai." },
  { id: 50, hanzi: "女儿", pinyin: "nǚér",   meaning: "con gái",         type: "danh từ", example: "她的女儿很可爱。 - Con gái cô ấy rất dễ thương." },
  { id: 51, hanzi: "朋友", pinyin: "péngyou",meaning: "bạn bè",          type: "danh từ", example: "他是我的好朋友。 - Anh ấy là bạn tốt của tôi." },
  { id: 52, hanzi: "老师", pinyin: "lǎoshī", meaning: "giáo viên, thầy cô", type: "danh từ", example: "老师好！ - Chào thầy/cô!" },
  { id: 53, hanzi: "学生", pinyin: "xuésheng",meaning: "học sinh, sinh viên", type: "danh từ", example: "我是学生。 - Tôi là học sinh." },
  { id: 54, hanzi: "同学", pinyin: "tóngxué",meaning: "bạn cùng lớp",    type: "danh từ", example: "他是我的同学。 - Anh ấy là bạn cùng lớp của tôi." },
  { id: 55, hanzi: "医生", pinyin: "yīshēng",meaning: "bác sĩ",          type: "danh từ", example: "他是医生。 - Ông ấy là bác sĩ." },

  // Địa điểm
  { id: 56, hanzi: "中国", pinyin: "Zhōngguó",meaning: "Trung Quốc",    type: "địa danh", example: "我去中国。 - Tôi đến Trung Quốc." },
  { id: 57, hanzi: "北京", pinyin: "Běijīng", meaning: "Bắc Kinh",      type: "địa danh", example: "北京很大。 - Bắc Kinh rất lớn." },
  { id: 58, hanzi: "家",   pinyin: "jiā",     meaning: "nhà, gia đình",  type: "danh từ", example: "我回家了。 - Tôi về nhà rồi." },
  { id: 59, hanzi: "学校", pinyin: "xuéxiào", meaning: "trường học",     type: "danh từ", example: "我去学校。 - Tôi đến trường." },
  { id: 60, hanzi: "商店", pinyin: "shāngdiàn",meaning: "cửa hàng",     type: "danh từ", example: "我去商店买东西。 - Tôi đến cửa hàng mua đồ." },
  { id: 61, hanzi: "饭店", pinyin: "fàndiàn", meaning: "nhà hàng, khách sạn", type: "danh từ", example: "我们去饭店吃饭。 - Chúng ta đến nhà hàng ăn." },
  { id: 62, hanzi: "医院", pinyin: "yīyuàn",  meaning: "bệnh viện",      type: "danh từ", example: "去医院看病。 - Đến bệnh viện khám bệnh." },
  { id: 63, hanzi: "里",   pinyin: "lǐ",      meaning: "trong, bên trong", type: "giới từ", example: "家里。 - Trong nhà." },
  { id: 64, hanzi: "上",   pinyin: "shàng",   meaning: "trên, lên",       type: "giới từ", example: "桌子上。 - Trên bàn." },
  { id: 65, hanzi: "下",   pinyin: "xià",     meaning: "dưới, xuống",    type: "giới từ", example: "桌子下。 - Dưới bàn." },

  // Đồ vật
  { id: 66, hanzi: "书",   pinyin: "shū",    meaning: "sách",            type: "danh từ", example: "我看书。 - Tôi đọc sách." },
  { id: 67, hanzi: "本子", pinyin: "běnzi",  meaning: "quyển vở",        type: "danh từ", example: "我买了一个本子。 - Tôi mua một quyển vở." },
  { id: 68, hanzi: "桌子", pinyin: "zhuōzi", meaning: "cái bàn",         type: "danh từ", example: "桌子上有书。 - Trên bàn có sách." },
  { id: 69, hanzi: "椅子", pinyin: "yǐzi",   meaning: "cái ghế",         type: "danh từ", example: "请坐椅子。 - Mời ngồi ghế." },
  { id: 70, hanzi: "杯子", pinyin: "bēizi",  meaning: "cái cốc, ly",     type: "danh từ", example: "喝水的杯子。 - Ly đựng nước." },
  { id: 71, hanzi: "钱",   pinyin: "qián",   meaning: "tiền",            type: "danh từ", example: "多少钱？ - Bao nhiêu tiền?" },
  { id: 72, hanzi: "电话", pinyin: "diànhuà",meaning: "điện thoại",      type: "danh từ", example: "打电话。 - Gọi điện thoại." },
  { id: 73, hanzi: "电脑", pinyin: "diànnǎo",meaning: "máy tính",        type: "danh từ", example: "我用电脑工作。 - Tôi dùng máy tính làm việc." },
  { id: 74, hanzi: "电视", pinyin: "diànshì",meaning: "TV, ti vi",       type: "danh từ", example: "看电视。 - Xem TV." },
  { id: 75, hanzi: "东西", pinyin: "dōngxi", meaning: "đồ vật, thứ",    type: "danh từ", example: "买东西。 - Mua đồ." },

  // Ăn uống
  { id: 76, hanzi: "吃",   pinyin: "chī",    meaning: "ăn",              type: "động từ", example: "我吃饭了。 - Tôi ăn cơm rồi." },
  { id: 77, hanzi: "喝",   pinyin: "hē",     meaning: "uống",            type: "động từ", example: "喝水。 - Uống nước." },
  { id: 78, hanzi: "饭",   pinyin: "fàn",    meaning: "cơm, bữa ăn",    type: "danh từ", example: "吃饭了吗？ - Ăn cơm chưa?" },
  { id: 79, hanzi: "菜",   pinyin: "cài",    meaning: "rau, món ăn",     type: "danh từ", example: "吃菜。 - Ăn rau/món ăn." },
  { id: 80, hanzi: "水",   pinyin: "shuǐ",   meaning: "nước",            type: "danh từ", example: "喝水。 - Uống nước." },
  { id: 81, hanzi: "茶",   pinyin: "chá",    meaning: "trà",             type: "danh từ", example: "喝茶。 - Uống trà." },
  { id: 82, hanzi: "苹果", pinyin: "píngguǒ",meaning: "táo",             type: "danh từ", example: "吃苹果。 - Ăn táo." },
  { id: 83, hanzi: "米饭", pinyin: "mǐfàn",  meaning: "cơm trắng",      type: "danh từ", example: "吃米饭。 - Ăn cơm." },
  { id: 84, hanzi: "面条", pinyin: "miàntiáo",meaning: "mì sợi",         type: "danh từ", example: "吃面条。 - Ăn mì." },

  // Động từ thông dụng
  { id: 85,  hanzi: "是",   pinyin: "shì",    meaning: "là (động từ)",   type: "động từ", example: "我是中国人。 - Tôi là người Trung Quốc." },
  { id: 86,  hanzi: "有",   pinyin: "yǒu",    meaning: "có",             type: "động từ", example: "我有一本书。 - Tôi có một quyển sách." },
  { id: 87,  hanzi: "在",   pinyin: "zài",    meaning: "ở, đang (ở)",   type: "động từ", example: "我在家。 - Tôi ở nhà." },
  { id: 88,  hanzi: "来",   pinyin: "lái",    meaning: "đến, lại",       type: "động từ", example: "请进来。 - Mời vào." },
  { id: 89,  hanzi: "去",   pinyin: "qù",     meaning: "đi, đến",        type: "động từ", example: "我去北京。 - Tôi đi Bắc Kinh." },
  { id: 90,  hanzi: "回",   pinyin: "huí",    meaning: "về, quay lại",  type: "động từ", example: "我回家。 - Tôi về nhà." },
  { id: 91,  hanzi: "看",   pinyin: "kàn",    meaning: "xem, nhìn",      type: "động từ", example: "看书。 - Đọc sách." },
  { id: 92,  hanzi: "说",   pinyin: "shuō",   meaning: "nói",            type: "động từ", example: "说中文。 - Nói tiếng Trung." },
  { id: 93,  hanzi: "听",   pinyin: "tīng",   meaning: "nghe",           type: "động từ", example: "听音乐。 - Nghe nhạc." },
  { id: 94,  hanzi: "写",   pinyin: "xiě",    meaning: "viết",           type: "động từ", example: "写字。 - Viết chữ." },
  { id: 95,  hanzi: "读",   pinyin: "dú",     meaning: "đọc",            type: "động từ", example: "读书。 - Đọc sách." },
  { id: 96,  hanzi: "学习", pinyin: "xuéxí",  meaning: "học tập, học",  type: "động từ", example: "我学习中文。 - Tôi học tiếng Trung." },
  { id: 97,  hanzi: "工作", pinyin: "gōngzuò",meaning: "làm việc, công việc", type: "động từ/danh từ", example: "我工作了。 - Tôi đi làm rồi." },
  { id: 98,  hanzi: "睡觉", pinyin: "shuìjiào",meaning: "ngủ",           type: "động từ", example: "我去睡觉了。 - Tôi đi ngủ rồi." },
  { id: 99,  hanzi: "起床", pinyin: "qǐchuáng",meaning: "dậy (ra giường)", type: "động từ", example: "我七点起床。 - Tôi dậy lúc 7 giờ." },
  { id: 100, hanzi: "做",   pinyin: "zuò",    meaning: "làm, nấu",       type: "động từ", example: "做作业。 - Làm bài tập." },
  { id: 101, hanzi: "买",   pinyin: "mǎi",    meaning: "mua",            type: "động từ", example: "买东西。 - Mua đồ." },
  { id: 102, hanzi: "打电话",pinyin:"dǎ diànhuà",meaning:"gọi điện thoại", type:"động từ", example:"我打电话给你。 - Tôi gọi điện cho bạn." },
  { id: 103, hanzi: "开",   pinyin: "kāi",    meaning: "mở, lái (xe)",  type: "động từ", example: "开门。 - Mở cửa." },
  { id: 104, hanzi: "住",   pinyin: "zhù",    meaning: "sống, ở",        type: "động từ", example: "我住在北京。 - Tôi sống ở Bắc Kinh." },
  { id: 105, hanzi: "坐",   pinyin: "zuò",    meaning: "ngồi, đi (phương tiện)", type: "động từ", example: "坐飞机。 - Đi máy bay." },

  // Tính từ
  { id: 106, hanzi: "好",   pinyin: "hǎo",    meaning: "tốt, khỏe",     type: "tính từ", example: "你好！ - Bạn khỏe không?" },
  { id: 107, hanzi: "大",   pinyin: "dà",     meaning: "to, lớn",        type: "tính từ", example: "很大的房子。 - Căn nhà rất lớn." },
  { id: 108, hanzi: "小",   pinyin: "xiǎo",   meaning: "nhỏ, bé",        type: "tính từ", example: "很小的孩子。 - Đứa bé rất nhỏ." },
  { id: 109, hanzi: "多",   pinyin: "duō",    meaning: "nhiều",           type: "tính từ", example: "很多人。 - Rất nhiều người." },
  { id: 110, hanzi: "少",   pinyin: "shǎo",   meaning: "ít",              type: "tính từ", example: "人很少。 - Người rất ít." },
  { id: 111, hanzi: "冷",   pinyin: "lěng",   meaning: "lạnh",            type: "tính từ", example: "今天很冷。 - Hôm nay rất lạnh." },
  { id: 112, hanzi: "热",   pinyin: "rè",     meaning: "nóng",            type: "tính từ", example: "天气很热。 - Thời tiết rất nóng." },
  { id: 113, hanzi: "高兴", pinyin: "gāoxìng",meaning: "vui, hạnh phúc", type: "tính từ", example: "我很高兴。 - Tôi rất vui." },
  { id: 114, hanzi: "漂亮", pinyin: "piàoliang",meaning: "đẹp",           type: "tính từ", example: "她很漂亮。 - Cô ấy rất đẹp." },
  { id: 115, hanzi: "贵",   pinyin: "guì",    meaning: "đắt",             type: "tính từ", example: "太贵了！ - Đắt quá!" },
  { id: 116, hanzi: "便宜", pinyin: "piányí", meaning: "rẻ",              type: "tính từ", example: "很便宜。 - Rất rẻ." },
  { id: 117, hanzi: "好吃", pinyin: "hǎochī", meaning: "ngon",            type: "tính từ", example: "这个菜很好吃。 - Món này rất ngon." },
  { id: 118, hanzi: "累",   pinyin: "lèi",    meaning: "mệt",             type: "tính từ", example: "我很累。 - Tôi rất mệt." },

  // Phó từ / Liên từ
  { id: 119, hanzi: "不",   pinyin: "bù",     meaning: "không (phủ định)", type: "phó từ", example: "我不去。 - Tôi không đi." },
  { id: 120, hanzi: "没",   pinyin: "méi",    meaning: "không có, chưa", type: "phó từ", example: "没有。 - Không có." },
  { id: 121, hanzi: "很",   pinyin: "hěn",    meaning: "rất",             type: "phó từ", example: "很好。 - Rất tốt." },
  { id: 122, hanzi: "太",   pinyin: "tài",    meaning: "quá",             type: "phó từ", example: "太贵了。 - Quá đắt." },
  { id: 123, hanzi: "都",   pinyin: "dōu",    meaning: "đều, tất cả",    type: "phó từ", example: "我们都是学生。 - Chúng tôi đều là học sinh." },
  { id: 124, hanzi: "也",   pinyin: "yě",     meaning: "cũng",            type: "phó từ", example: "我也是。 - Tôi cũng vậy." },
  { id: 125, hanzi: "一起", pinyin: "yīqǐ",   meaning: "cùng nhau",       type: "phó từ", example: "我们一起去。 - Chúng ta cùng đi." },
  { id: 126, hanzi: "和",   pinyin: "hé",     meaning: "và, cùng",        type: "liên từ", example: "我和你。 - Tôi và bạn." },
  { id: 127, hanzi: "但是", pinyin: "dànshì", meaning: "nhưng mà",        type: "liên từ", example: "我想去，但是没时间。 - Tôi muốn đi nhưng không có thời gian." },
  { id: 128, hanzi: "因为", pinyin: "yīnwèi", meaning: "vì, bởi vì",     type: "liên từ", example: "因为下雨，我没去。 - Vì trời mưa tôi không đi." },
  { id: 129, hanzi: "所以", pinyin: "suǒyǐ",  meaning: "vì vậy, cho nên", type: "liên từ", example: "所以我在家。 - Vì vậy tôi ở nhà." },

  // Chào hỏi & Giao tiếp
  { id: 130, hanzi: "你好", pinyin: "nǐ hǎo", meaning: "xin chào",       type: "chào hỏi", example: "你好！ - Xin chào!" },
  { id: 131, hanzi: "再见", pinyin: "zàijiàn",meaning: "tạm biệt",        type: "chào hỏi", example: "再见！ - Tạm biệt!" },
  { id: 132, hanzi: "谢谢", pinyin: "xièxie", meaning: "cảm ơn",          type: "chào hỏi", example: "谢谢你！ - Cảm ơn bạn!" },
  { id: 133, hanzi: "对不起",pinyin:"duìbuqǐ",meaning: "xin lỗi",         type: "chào hỏi", example: "对不起！ - Xin lỗi!" },
  { id: 134, hanzi: "没关系",pinyin:"méiguānxi",meaning:"không sao",      type: "chào hỏi", example: "没关系！ - Không sao!" },
  { id: 135, hanzi: "请",   pinyin: "qǐng",   meaning: "xin, mời",        type: "chào hỏi", example: "请进！ - Mời vào!" },
  { id: 136, hanzi: "喂",   pinyin: "wèi",    meaning: "alo (nghe điện thoại)", type: "chào hỏi", example: "喂，你好！ - Alo, xin chào!" },

  // Phương tiện & Đi lại
  { id: 137, hanzi: "电车", pinyin: "diànchē", meaning: "xe điện",        type: "danh từ", example: "坐电车。 - Đi xe điện." },
  { id: 138, hanzi: "出租车",pinyin:"chūzūchē",meaning: "xe taxi",        type: "danh từ", example: "坐出租车。 - Đi taxi." },
  { id: 139, hanzi: "飞机", pinyin: "fēijī",   meaning: "máy bay",        type: "danh từ", example: "坐飞机去北京。 - Đi máy bay đến Bắc Kinh." },
  { id: 140, hanzi: "火车", pinyin: "huǒchē",  meaning: "tàu hỏa",        type: "danh từ", example: "坐火车旅行。 - Đi tàu hỏa du lịch." },

  // Thể thao & Giải trí
  { id: 141, hanzi: "踢足球",pinyin:"tī zúqiú",meaning: "đá bóng",        type: "động từ", example: "我喜欢踢足球。 - Tôi thích đá bóng." },
  { id: 142, hanzi: "游泳", pinyin: "yóuyǒng", meaning: "bơi lội",        type: "động từ", example: "去游泳。 - Đi bơi." },
  { id: 143, hanzi: "音乐", pinyin: "yīnyuè",  meaning: "âm nhạc",        type: "danh từ", example: "听音乐。 - Nghe nhạc." },
  { id: 144, hanzi: "电影", pinyin: "diànyǐng",meaning: "phim, điện ảnh", type: "danh từ", example: "看电影。 - Xem phim." },

  // Thời tiết
  { id: 145, hanzi: "天气", pinyin: "tiānqì",  meaning: "thời tiết",      type: "danh từ", example: "今天天气怎么样？ - Hôm nay thời tiết thế nào?" },
  { id: 146, hanzi: "下雨", pinyin: "xià yǔ",  meaning: "mưa",            type: "động từ", example: "今天下雨了。 - Hôm nay trời mưa." },
  { id: 147, hanzi: "下雪", pinyin: "xià xuě", meaning: "tuyết rơi",      type: "động từ", example: "今天下雪了。 - Hôm nay có tuyết." },

  // Lượng từ & Giới từ
  { id: 148, hanzi: "个",   pinyin: "gè",      meaning: "cái, con, cây (lượng từ chung)", type: "lượng từ", example: "一个苹果。 - Một quả táo." },
  { id: 149, hanzi: "的",   pinyin: "de",      meaning: "của (trợ từ)",   type: "trợ từ", example: "我的书。 - Sách của tôi." },
  { id: 150, hanzi: "了",   pinyin: "le",      meaning: "rồi (trợ từ hoàn thành)", type: "trợ từ", example: "我吃饭了。 - Tôi ăn cơm rồi." },
  // Màu sắc
  { id: 151, hanzi: "红色", pinyin: "hóngsè",  meaning: "màu đỏ",           type: "tính từ", example: "红色的苹果。 - Quả táo màu đỏ." },
  { id: 152, hanzi: "白色", pinyin: "báisè",   meaning: "màu trắng",        type: "tính từ", example: "白色的衬衫。 - Áo sơ mi màu trắng." },
  { id: 153, hanzi: "黑色", pinyin: "hēisè",   meaning: "màu đen",          type: "tính từ", example: "黑色的鞋子。 - Đôi giày màu đen." },
  { id: 154, hanzi: "黄色", pinyin: "huángsè", meaning: "màu vàng",         type: "tính từ", example: "黄色的香蕉。 - Quả chuối màu vàng." },
  { id: 155, hanzi: "蓝色", pinyin: "lánsè",   meaning: "màu xanh lam",     type: "tính từ", example: "蓝色的天空。 - Bầu trời màu xanh." },

  // Cơ thể người
  { id: 156, hanzi: "眼睛", pinyin: "yǎnjing",  meaning: "mắt",             type: "danh từ", example: "眼睛很大。 - Mắt rất to." },
  { id: 157, hanzi: "耳朵", pinyin: "ěrduo",    meaning: "tai",             type: "danh từ", example: "耳朵很小。 - Tai rất nhỏ." },
  { id: 158, hanzi: "鼻子", pinyin: "bízi",     meaning: "mũi",             type: "danh từ", example: "鼻子很高。 - Mũi rất cao." },
  { id: 159, hanzi: "嘴",   pinyin: "zuǐ",      meaning: "miệng",           type: "danh từ", example: "张开嘴。 - Há miệng ra." },
  { id: 160, hanzi: "手",   pinyin: "shǒu",     meaning: "tay",             type: "danh từ", example: "洗手。 - Rửa tay." },
  { id: 161, hanzi: "脚",   pinyin: "jiǎo",     meaning: "chân",            type: "danh từ", example: "脚很大。 - Chân rất to." },
  { id: 162, hanzi: "头",   pinyin: "tóu",      meaning: "đầu",             type: "danh từ", example: "头疼。 - Đau đầu." },

  // Nhà cửa & Đồ đạc
  { id: 163, hanzi: "房间", pinyin: "fángjiān", meaning: "phòng",           type: "danh từ", example: "我的房间很大。 - Phòng tôi rất rộng." },
  { id: 164, hanzi: "门",   pinyin: "mén",      meaning: "cửa (cổng)",      type: "danh từ", example: "关门。 - Đóng cửa." },
  { id: 165, hanzi: "窗户", pinyin: "chuānghu", meaning: "cửa sổ",          type: "danh từ", example: "开窗户。 - Mở cửa sổ." },
  { id: 166, hanzi: "床",   pinyin: "chuáng",   meaning: "giường",          type: "danh từ", example: "睡在床上。 - Ngủ trên giường." },
  { id: 167, hanzi: "衣服", pinyin: "yīfu",     meaning: "quần áo",         type: "danh từ", example: "买衣服。 - Mua quần áo." },
  { id: 168, hanzi: "鞋",   pinyin: "xié",      meaning: "giày dép",        type: "danh từ", example: "穿鞋。 - Đi giày." },

  // Thức ăn & Đồ uống thêm
  { id: 169, hanzi: "鸡蛋", pinyin: "jīdàn",    meaning: "trứng gà",        type: "danh từ", example: "吃鸡蛋。 - Ăn trứng." },
  { id: 170, hanzi: "牛奶", pinyin: "niúnǎi",   meaning: "sữa bò",          type: "danh từ", example: "喝牛奶。 - Uống sữa." },
  { id: 171, hanzi: "面包", pinyin: "miànbāo",  meaning: "bánh mì",         type: "danh từ", example: "吃面包。 - Ăn bánh mì." },
  { id: 172, hanzi: "水果", pinyin: "shuǐguǒ",  meaning: "trái cây",        type: "danh từ", example: "吃水果。 - Ăn trái cây." },
  { id: 173, hanzi: "香蕉", pinyin: "xiāngjiāo",meaning: "chuối",            type: "danh từ", example: "吃香蕉。 - Ăn chuối." },

  // Cảm xúc & Trạng thái
  { id: 174, hanzi: "喜欢", pinyin: "xǐhuān",   meaning: "thích",           type: "động từ", example: "我喜欢中文。 - Tôi thích tiếng Trung." },
  { id: 175, hanzi: "想",   pinyin: "xiǎng",    meaning: "muốn, nghĩ",      type: "động từ", example: "我想吃饭。 - Tôi muốn ăn cơm." },
  { id: 176, hanzi: "知道", pinyin: "zhīdào",   meaning: "biết",            type: "động từ", example: "我知道了。 - Tôi biết rồi." },
  { id: 177, hanzi: "认识", pinyin: "rènshi",   meaning: "quen biết, nhận ra", type: "động từ", example: "我认识他。 - Tôi quen anh ấy." },
  { id: 178, hanzi: "高兴", pinyin: "gāoxìng",  meaning: "vui vẻ, hạnh phúc", type: "tính từ", example: "很高兴认识你！ - Rất vui được biết bạn!" },
  { id: 179, hanzi: "难",   pinyin: "nán",      meaning: "khó",             type: "tính từ", example: "这道题很难。 - Bài này rất khó." },
  { id: 180, hanzi: "容易", pinyin: "róngyì",   meaning: "dễ",              type: "tính từ", example: "这很容易。 - Cái này rất dễ." },
  { id: 181, hanzi: "对",   pinyin: "duì",      meaning: "đúng, phải",      type: "tính từ", example: "对！ - Đúng rồi!" },
  { id: 182, hanzi: "错",   pinyin: "cuò",      meaning: "sai",             type: "tính từ", example: "我错了。 - Tôi sai rồi." },

  // Hành động thêm
  { id: 183, hanzi: "打",   pinyin: "dǎ",       meaning: "đánh, gõ, gọi",   type: "động từ", example: "打球。 - Đánh bóng." },
  { id: 184, hanzi: "叫",   pinyin: "jiào",     meaning: "gọi, tên là",     type: "động từ", example: "你叫什么名字？ - Bạn tên là gì?" },
  { id: 185, hanzi: "告诉", pinyin: "gàosu",    meaning: "nói cho biết",    type: "động từ", example: "告诉我。 - Nói cho tôi biết." },
  { id: 186, hanzi: "等",   pinyin: "děng",     meaning: "chờ đợi",         type: "động từ", example: "等一下。 - Chờ một chút." },
  { id: 187, hanzi: "找",   pinyin: "zhǎo",     meaning: "tìm",             type: "động từ", example: "找工作。 - Tìm việc làm." },
  { id: 188, hanzi: "穿",   pinyin: "chuān",    meaning: "mặc, đi (giày)",  type: "động từ", example: "穿衣服。 - Mặc quần áo." },
  { id: 189, hanzi: "走",   pinyin: "zǒu",      meaning: "đi bộ, đi",       type: "động từ", example: "走路。 - Đi bộ." },
  { id: 190, hanzi: "跑",   pinyin: "pǎo",      meaning: "chạy",            type: "động từ", example: "跑步。 - Chạy bộ." },

  // Địa điểm & Vị trí thêm
  { id: 191, hanzi: "前面", pinyin: "qiánmiàn", meaning: "phía trước",      type: "danh từ", example: "前面有一家餐厅。 - Phía trước có một nhà hàng." },
  { id: 192, hanzi: "后面", pinyin: "hòumiàn",  meaning: "phía sau",        type: "danh từ", example: "后面是学校。 - Phía sau là trường học." },
  { id: 193, hanzi: "旁边", pinyin: "pángbiān", meaning: "bên cạnh",        type: "danh từ", example: "旁边有人。 - Bên cạnh có người." },
  { id: 194, hanzi: "左边", pinyin: "zuǒbiān",  meaning: "bên trái",        type: "danh từ", example: "在左边。 - Ở bên trái." },
  { id: 195, hanzi: "右边", pinyin: "yòubiān",  meaning: "bên phải",        type: "danh từ", example: "在右边。 - Ở bên phải." },

  // Lượng từ & Từ bổ sung
  { id: 196, hanzi: "次",   pinyin: "cì",       meaning: "lần",             type: "lượng từ", example: "一次。 - Một lần." },
  { id: 197, hanzi: "块",   pinyin: "kuài",     meaning: "đồng (đơn vị tiền tệ)", type: "lượng từ", example: "十块钱。 - Mười đồng." },
  { id: 198, hanzi: "名字", pinyin: "míngzi",   meaning: "tên",             type: "danh từ", example: "你叫什么名字？ - Tên bạn là gì?" },
  { id: 199, hanzi: "问题", pinyin: "wèntí",    meaning: "vấn đề, câu hỏi", type: "danh từ", example: "有问题吗？ - Có vấn đề gì không?" },
  { id: 200, hanzi: "时间", pinyin: "shíjiān",  meaning: "thời gian",       type: "danh từ", example: "没有时间。 - Không có thời gian." },

  // ── Bổ sung từ danh sách mở rộng (bỏ qua từ đã có) ──

  // Phủ định & Cụm thông dụng
  { id: 201, hanzi: "没有", pinyin: "méiyǒu",   meaning: "không có, chưa",          type: "phó từ",   example: "我没有钱。 - Tôi không có tiền." },
  { id: 202, hanzi: "这个", pinyin: "zhège",     meaning: "cái này, việc này",        type: "đại từ",   example: "这个是什么？ - Cái này là gì?" },
  { id: 203, hanzi: "可以", pinyin: "kěyǐ",     meaning: "có thể, được phép",        type: "trợ động", example: "我可以进来吗？ - Tôi vào được không?" },
  { id: 204, hanzi: "如果", pinyin: "rúguǒ",    meaning: "nếu, nếu như",             type: "liên từ",  example: "如果你来，我很高兴。 - Nếu bạn đến tôi rất vui." },
  { id: 205, hanzi: "这样", pinyin: "zhèyàng",  meaning: "như vậy, như thế này",     type: "đại từ",   example: "你不能这样做。 - Bạn không thể làm như vậy." },
  { id: 206, hanzi: "自己", pinyin: "zìjǐ",     meaning: "tự mình, bản thân",        type: "đại từ",   example: "自己做。 - Tự mình làm." },
  { id: 207, hanzi: "这里", pinyin: "zhèlǐ",    meaning: "ở đây, chỗ này",           type: "đại từ",   example: "请在这里等我。 - Hãy chờ tôi ở đây." },
  { id: 208, hanzi: "已经", pinyin: "yǐjīng",   meaning: "đã, rồi",                  type: "phó từ",   example: "我已经吃了。 - Tôi đã ăn rồi." },
  { id: 209, hanzi: "觉得", pinyin: "juéde",    meaning: "cảm thấy, thấy rằng",      type: "động từ",  example: "我觉得很累。 - Tôi cảm thấy rất mệt." },
  { id: 210, hanzi: "这么", pinyin: "zhème",    meaning: "như thế này, vậy",          type: "phó từ",   example: "怎么这么贵？ - Sao đắt vậy?" },
  { id: 211, hanzi: "先生", pinyin: "xiānsheng",meaning: "thầy, ông, chồng",          type: "danh từ",  example: "王先生，你好！ - Chào ông Vương!" },
  { id: 212, hanzi: "可能", pinyin: "kěnéng",   meaning: "có thể, có lẽ",            type: "phó từ",   example: "他可能来。 - Có lẽ anh ấy sẽ đến." },
  { id: 213, hanzi: "需要", pinyin: "xūyào",    meaning: "cần, cần phải",            type: "động từ",  example: "我需要帮助。 - Tôi cần giúp đỡ." },
  { id: 214, hanzi: "是的", pinyin: "shì de",   meaning: "đúng vậy, phải",           type: "cảm thán", example: "是的，我是。 - Đúng vậy, đó là tôi." },
  { id: 215, hanzi: "那么", pinyin: "nàme",     meaning: "như vậy, thế thì",          type: "liên từ",  example: "那么，我们走吧。 - Vậy thì chúng ta đi thôi." },
  { id: 216, hanzi: "那个", pinyin: "nàgè",     meaning: "cái đó, cái kia",           type: "đại từ",   example: "那个是谁的？ - Cái đó là của ai?" },
  { id: 217, hanzi: "应该", pinyin: "yīnggāi",  meaning: "nên, cần phải",            type: "trợ động", example: "你应该去看医生。 - Bạn nên đi khám bác sĩ." },
  { id: 218, hanzi: "孩子", pinyin: "háizi",    meaning: "trẻ con, con cái",          type: "danh từ",  example: "孩子们喜欢玩。 - Trẻ con thích chơi." },
  { id: 219, hanzi: "起来", pinyin: "qǐlái",    meaning: "đứng dậy, nổi dậy",        type: "động từ",  example: "起来！ - Dậy đi!" },
  { id: 220, hanzi: "这些", pinyin: "zhèxiē",   meaning: "những cái này",             type: "đại từ",   example: "这些都是我的。 - Những cái này đều là của tôi." },
  { id: 221, hanzi: "还有", pinyin: "hái yǒu",  meaning: "còn có, ngoài ra",          type: "liên từ",  example: "还有什么？ - Còn gì nữa không?" },
  { id: 222, hanzi: "开始", pinyin: "kāishǐ",   meaning: "bắt đầu",                  type: "động từ",  example: "开始学习。 - Bắt đầu học." },
  { id: 223, hanzi: "然后", pinyin: "ránhòu",   meaning: "sau đó, tiếp theo",         type: "liên từ",  example: "先吃饭，然后再去。 - Ăn cơm trước, sau đó mới đi." },
  { id: 224, hanzi: "一样", pinyin: "yīyàng",   meaning: "giống nhau, như nhau",      type: "tính từ",  example: "我们一样高。 - Chúng ta cao bằng nhau." },
  { id: 225, hanzi: "事情", pinyin: "shìqíng",  meaning: "sự việc, chuyện",           type: "danh từ",  example: "这件事情很重要。 - Chuyện này rất quan trọng." },
  { id: 226, hanzi: "就是", pinyin: "jiùshì",   meaning: "chính là, đúng là",         type: "phó từ",   example: "就是这个！ - Chính là cái này!" },
  { id: 227, hanzi: "所有", pinyin: "suǒyǒu",   meaning: "tất cả, toàn bộ",           type: "đại từ",   example: "所有人都来了。 - Tất cả mọi người đã đến." },
  { id: 228, hanzi: "一下", pinyin: "yīxià",    meaning: "một chút, thử xem",         type: "phó từ",   example: "等一下。 - Chờ một chút." },
  { id: 229, hanzi: "非常", pinyin: "fēicháng",  meaning: "rất, vô cùng",             type: "phó từ",   example: "非常好！ - Rất tốt!" },
  { id: 230, hanzi: "看到", pinyin: "kàn dào",  meaning: "nhìn thấy, trông thấy",     type: "động từ",  example: "我看到他了。 - Tôi thấy anh ấy rồi." },
  { id: 231, hanzi: "希望", pinyin: "xīwàng",   meaning: "hy vọng, mong muốn",        type: "động từ",  example: "我希望你快乐。 - Tôi hy vọng bạn hạnh phúc." },
  { id: 232, hanzi: "那些", pinyin: "nàxiē",    meaning: "những cái đó, những ấy",    type: "đại từ",   example: "那些都是新的。 - Những cái đó đều mới." },
  { id: 233, hanzi: "当然", pinyin: "dāngrán",  meaning: "đương nhiên, tất nhiên",    type: "phó từ",   example: "当然可以！ - Đương nhiên được!" },
  { id: 234, hanzi: "也许", pinyin: "yěxǔ",     meaning: "có lẽ, biết đâu",           type: "phó từ",   example: "也许他明天来。 - Có lẽ anh ấy sẽ đến ngày mai." },
  { id: 235, hanzi: "相信", pinyin: "xiāngxìn", meaning: "tin tưởng, tin tưởng vào",  type: "động từ",  example: "我相信你。 - Tôi tin bạn." },
  { id: 236, hanzi: "认为", pinyin: "rènwéi",   meaning: "cho rằng, cho là",           type: "động từ",  example: "我认为这是对的。 - Tôi cho rằng điều này đúng." },
  { id: 237, hanzi: "这儿", pinyin: "zhèr",     meaning: "ở đây, chỗ này",            type: "đại từ",   example: "请坐这儿。 - Mời ngồi đây." },
  { id: 238, hanzi: "明白", pinyin: "míngbái",  meaning: "hiểu, rõ ràng",             type: "động từ",  example: "你明白了吗？ - Bạn hiểu chưa?" },
  { id: 239, hanzi: "一直", pinyin: "yīzhí",    meaning: "mãi, luôn luôn, liên tục",  type: "phó từ",   example: "我一直等你。 - Tôi luôn chờ bạn." },
  { id: 240, hanzi: "地方", pinyin: "dìfang",   meaning: "địa phương, nơi, chỗ",      type: "danh từ",  example: "这个地方很美。 - Nơi này rất đẹp." },
  { id: 241, hanzi: "不过", pinyin: "bùguò",    meaning: "nhưng, tuy nhiên",           type: "liên từ",  example: "我想去，不过没时间。 - Tôi muốn đi nhưng không có thời gian." },
  { id: 242, hanzi: "发生", pinyin: "fāshēng",  meaning: "xảy ra, phát sinh",          type: "động từ",  example: "发生了什么？ - Chuyện gì đã xảy ra?" },
  { id: 243, hanzi: "回来", pinyin: "huílái",   meaning: "trở về, quay lại",           type: "động từ",  example: "快回来！ - Quay lại nhanh!" },
  { id: 244, hanzi: "准备", pinyin: "zhǔnbèi",  meaning: "chuẩn bị, dự định",         type: "động từ",  example: "我准备好了。 - Tôi đã chuẩn bị xong." },
  { id: 245, hanzi: "找到", pinyin: "zhǎodào",  meaning: "tìm thấy",                  type: "động từ",  example: "我找到了！ - Tôi tìm thấy rồi!" },
  { id: 246, hanzi: "一切", pinyin: "yīqiè",    meaning: "tất cả, hết thảy",           type: "đại từ",   example: "一切都好。 - Mọi thứ đều tốt." },
  { id: 247, hanzi: "抱歉", pinyin: "bàoqiàn",  meaning: "xin lỗi, ân hận",           type: "tính từ",  example: "非常抱歉！ - Rất xin lỗi!" },
  { id: 248, hanzi: "感觉", pinyin: "gǎnjué",   meaning: "cảm giác, cảm thấy",         type: "động từ",  example: "我感觉很好。 - Tôi cảm thấy rất tốt." },
  { id: 249, hanzi: "只是", pinyin: "zhǐshì",   meaning: "chỉ là, nhưng",             type: "phó từ",   example: "我只是想帮你。 - Tôi chỉ muốn giúp bạn." },
  { id: 250, hanzi: "出来", pinyin: "chūlái",   meaning: "đi ra, ra ngoài",            type: "động từ",  example: "请出来！ - Hãy ra ngoài!" },

  { id: 251, hanzi: "不要", pinyin: "bùyào",    meaning: "đừng, không được",           type: "phó từ",   example: "不要走！ - Đừng đi!" },
  { id: 252, hanzi: "离开", pinyin: "líkāi",    meaning: "rời đi, chia tay",           type: "động từ",  example: "我要离开了。 - Tôi sắp rời đi rồi." },
  { id: 253, hanzi: "一点", pinyin: "yī diǎn",  meaning: "một chút, một ít",           type: "phó từ",   example: "一点都不好。 - Không tốt chút nào." },
  { id: 254, hanzi: "一定", pinyin: "yī dìng",  meaning: "nhất định, chắc chắn",       type: "phó từ",   example: "一定要来！ - Nhất định phải đến!" },
  { id: 255, hanzi: "还是", pinyin: "háishì",   meaning: "vẫn, hay là, hoặc",          type: "liên từ",  example: "你去还是不去？ - Bạn đi hay không?" },
  { id: 256, hanzi: "发现", pinyin: "fāxiàn",   meaning: "phát hiện, tìm ra",          type: "động từ",  example: "我发现了问题。 - Tôi phát hiện ra vấn đề." },
  { id: 257, hanzi: "而且", pinyin: "érqiě",    meaning: "mà còn, hơn nữa",            type: "liên từ",  example: "他聪明，而且努力。 - Anh ấy thông minh, mà còn chăm chỉ." },
  { id: 258, hanzi: "必须", pinyin: "bìxū",     meaning: "nhất định phải, bắt buộc",   type: "phó từ",   example: "你必须来。 - Bạn nhất định phải đến." },
  { id: 259, hanzi: "意思", pinyin: "yìsi",     meaning: "ý nghĩa, ý muốn nói",        type: "danh từ",  example: "你的意思是？ - Ý bạn là sao?" },
  { id: 260, hanzi: "不错", pinyin: "bùcuò",    meaning: "không tệ, khá tốt",          type: "tính từ",  example: "这个不错！ - Cái này không tệ!" },
  { id: 261, hanzi: "肯定", pinyin: "kěndìng",  meaning: "chắc chắn, khẳng định",      type: "phó từ",   example: "我肯定知道。 - Tôi chắc chắn biết." },
  { id: 262, hanzi: "为了", pinyin: "wèile",    meaning: "để (chỉ mục đích), vì",      type: "giới từ",  example: "为了你，我来了。 - Vì bạn, tôi đã đến." },
  { id: 263, hanzi: "第一", pinyin: "dì yī",    meaning: "thứ nhất, hạng nhất",        type: "số thứ tự",example: "第一名。 - Hạng nhất." },
  { id: 264, hanzi: "那样", pinyin: "nàyàng",   meaning: "như thế, như vậy",            type: "đại từ",   example: "就那样吧。 - Thôi như vậy đi." },
  { id: 265, hanzi: "大家", pinyin: "dàjiā",    meaning: "mọi người, tất cả mọi người", type: "đại từ",  example: "大家好！ - Chào mọi người!" },
  { id: 266, hanzi: "一些", pinyin: "yīxiē",    meaning: "một ít, một số",             type: "đại từ",   example: "给我一些时间。 - Cho tôi một ít thời gian." },
  { id: 267, hanzi: "那里", pinyin: "nàlǐ",     meaning: "ở đó, chỗ đó",              type: "đại từ",   example: "我在那里等你。 - Tôi chờ bạn ở đó." },
  { id: 268, hanzi: "以为", pinyin: "yǐwéi",    meaning: "tưởng là, ngỡ là",           type: "động từ",  example: "我以为你走了。 - Tôi tưởng bạn đã đi rồi." },
  { id: 269, hanzi: "过来", pinyin: "guòlái",   meaning: "lại đây, đến đây",            type: "động từ",  example: "快过来！ - Lại đây nhanh!" },
  { id: 270, hanzi: "生活", pinyin: "shēnghuó", meaning: "cuộc sống, đời sống",        type: "danh từ",  example: "生活很好。 - Cuộc sống rất tốt." },
  { id: 271, hanzi: "最后", pinyin: "zuìhòu",   meaning: "cuối cùng, sau cùng",         type: "phó từ",   example: "最后他来了。 - Cuối cùng anh ấy đã đến." },

  // Từ 101-200 trong danh sách người dùng (chưa có)
  { id: 272, hanzi: "之前", pinyin: "zhīqián",  meaning: "trước, trước khi",           type: "giới từ",  example: "吃饭之前洗手。 - Rửa tay trước khi ăn." },
  { id: 273, hanzi: "任何", pinyin: "rènhé",    meaning: "bất kỳ, bất luận cái gì",    type: "đại từ",   example: "任何问题都可以问。 - Bất kỳ câu hỏi nào cũng có thể hỏi." },
  { id: 274, hanzi: "很多", pinyin: "hěnduō",   meaning: "rất nhiều",                  type: "đại từ",   example: "很多人来了。 - Rất nhiều người đến." },
  { id: 275, hanzi: "这种", pinyin: "zhè zhǒng",meaning: "loại này, kiểu này",          type: "đại từ",   example: "这种情况很常见。 - Tình huống này rất phổ biến." },
  { id: 276, hanzi: "女人", pinyin: "nǚrén",    meaning: "phụ nữ, đàn bà",             type: "danh từ",  example: "她是一个好女人。 - Cô ấy là người phụ nữ tốt." },
  { id: 277, hanzi: "今晚", pinyin: "jīn wǎn",  meaning: "tối nay",                   type: "thời gian",example: "今晚你有空吗？ - Tối nay bạn có rảnh không?" },
  { id: 278, hanzi: "其他", pinyin: "qítā",     meaning: "cái khác, những người khác", type: "đại từ",   example: "其他人呢？ - Những người khác thì sao?" },
  { id: 279, hanzi: "记得", pinyin: "jìde",     meaning: "nhớ, còn nhớ",              type: "động từ",  example: "你记得我吗？ - Bạn còn nhớ tôi không?" },
  { id: 280, hanzi: "或者", pinyin: "huòzhě",   meaning: "hoặc, hay là",               type: "liên từ",  example: "你去或者不去？ - Bạn đi hay không đi?" },
  { id: 281, hanzi: "过去", pinyin: "guòqù",    meaning: "quá khứ, đã qua",            type: "danh từ",  example: "过去的事。 - Chuyện đã qua." },
  { id: 282, hanzi: "哪里", pinyin: "nǎlǐ",     meaning: "đâu, ở đâu, đâu phải",       type: "từ hỏi",   example: "你在哪里？ - Bạn ở đâu?" },
  { id: 283, hanzi: "担心", pinyin: "dānxīn",   meaning: "lo lắng, lo âu",             type: "động từ",  example: "不要担心！ - Đừng lo lắng!" },
  { id: 284, hanzi: "继续", pinyin: "jìxù",     meaning: "tiếp tục",                   type: "động từ",  example: "请继续说。 - Hãy tiếp tục nói." },
  { id: 285, hanzi: "女孩", pinyin: "nǚhái",    meaning: "cô gái",                     type: "danh từ",  example: "那个女孩很漂亮。 - Cô gái đó rất đẹp." },
  { id: 286, hanzi: "下来", pinyin: "xiàlái",   meaning: "xuống, đi xuống",             type: "động từ",  example: "从楼上下来。 - Đi xuống từ trên lầu." },
  { id: 287, hanzi: "父亲", pinyin: "fùqīn",    meaning: "cha, bố (trang trọng)",       type: "danh từ",  example: "我的父亲是医生。 - Cha tôi là bác sĩ." },
  { id: 288, hanzi: "以前", pinyin: "yǐqián",   meaning: "trước đây, ngày trước",       type: "thời gian",example: "以前我住在北京。 - Trước đây tôi sống ở Bắc Kinh." },
  { id: 289, hanzi: "美国", pinyin: "měiguó",   meaning: "nước Mỹ",                    type: "địa danh", example: "他在美国工作。 - Anh ấy làm việc ở Mỹ." },
  { id: 290, hanzi: "完全", pinyin: "wánquán",  meaning: "hoàn toàn, đầy đủ",          type: "phó từ",   example: "我完全同意。 - Tôi hoàn toàn đồng ý." },
  { id: 291, hanzi: "宝贝", pinyin: "bǎobèi",   meaning: "cục cưng, của báu",           type: "danh từ",  example: "你是我的宝贝。 - Em là cục cưng của anh." },
  { id: 292, hanzi: "可是", pinyin: "kěshì",    meaning: "nhưng, thế nhưng",            type: "liên từ",  example: "我想去，可是没钱。 - Tôi muốn đi nhưng không có tiền." },
  { id: 293, hanzi: "世界", pinyin: "shìjiè",   meaning: "thế giới",                   type: "danh từ",  example: "全世界。 - Toàn thế giới." },
  { id: 294, hanzi: "小时", pinyin: "xiǎoshí",  meaning: "tiếng đồng hồ, giờ",         type: "lượng từ", example: "两个小时。 - Hai tiếng đồng hồ." },
  { id: 295, hanzi: "重要", pinyin: "zhòngyào", meaning: "quan trọng",                 type: "tính từ",  example: "这很重要。 - Điều này rất quan trọng." },
  { id: 296, hanzi: "别人", pinyin: "biérén",   meaning: "người khác",                 type: "đại từ",   example: "不要管别人。 - Đừng quan tâm người khác." },
  { id: 297, hanzi: "男人", pinyin: "nánrén",   meaning: "đàn ông, nam giới",           type: "danh từ",  example: "他是一个男人。 - Anh ấy là đàn ông." },
  { id: 298, hanzi: "机会", pinyin: "jīhuì",    meaning: "cơ hội, dịp",                type: "danh từ",  example: "这是一个好机会。 - Đây là một cơ hội tốt." },
  { id: 299, hanzi: "出去", pinyin: "chūqù",    meaning: "ra ngoài, đi ra",             type: "động từ",  example: "我想出去走走。 - Tôi muốn ra ngoài đi dạo." },
  { id: 300, hanzi: "看见", pinyin: "kànjiàn",  meaning: "nhìn thấy, trông thấy",       type: "động từ",  example: "我看见你了。 - Tôi nhìn thấy bạn rồi." },

  { id: 301, hanzi: "好像", pinyin: "hǎoxiàng", meaning: "hình như, có vẻ",             type: "phó từ",   example: "他好像很累。 - Anh ấy có vẻ rất mệt." },
  { id: 302, hanzi: "得到", pinyin: "dédào",    meaning: "được, nhận được, đạt được",   type: "động từ",  example: "得到奖励。 - Nhận được phần thưởng." },
  { id: 303, hanzi: "警察", pinyin: "jǐngchá",  meaning: "cảnh sát",                   type: "danh từ",  example: "报警！ - Gọi cảnh sát!" },
  { id: 304, hanzi: "之后", pinyin: "zhīhòu",   meaning: "sau, sau khi",                type: "giới từ",  example: "吃饭之后休息。 - Sau khi ăn nghỉ ngơi." },
  { id: 305, hanzi: "分钟", pinyin: "fēnzhōng", meaning: "phút",                        type: "lượng từ", example: "五分钟。 - Năm phút." },
  { id: 306, hanzi: "如何", pinyin: "rúhé",     meaning: "làm sao, như thế nào",        type: "từ hỏi",   example: "你觉得如何？ - Bạn thấy thế nào?" },
  { id: 307, hanzi: "比赛", pinyin: "bǐsài",    meaning: "thi đấu, cuộc thi",           type: "danh từ",  example: "参加比赛。 - Tham gia thi đấu." },
  { id: 308, hanzi: "情况", pinyin: "qíngkuàng",meaning: "tình hình, tình huống",        type: "danh từ",  example: "情况不好。 - Tình hình không tốt." },
  { id: 309, hanzi: "关系", pinyin: "guānxì",   meaning: "quan hệ, liên quan",           type: "danh từ",  example: "没关系。 - Không sao." },
  { id: 310, hanzi: "女士", pinyin: "nǚshì",    meaning: "bà, cô (lịch sự)",            type: "danh từ",  example: "女士们，先生们。 - Các quý bà, quý ông." },
  { id: 311, hanzi: "马上", pinyin: "mǎshàng",  meaning: "lập tức, ngay lập tức",       type: "phó từ",   example: "马上回来！ - Lập tức quay lại!" },
  { id: 312, hanzi: "决定", pinyin: "juédìng",  meaning: "quyết định",                  type: "động từ",  example: "我决定去。 - Tôi quyết định đi." },
  { id: 313, hanzi: "根本", pinyin: "gēnběn",   meaning: "cơ bản, căn bản, trước giờ",  type: "phó từ",   example: "根本不对。 - Hoàn toàn sai." },
  { id: 314, hanzi: "关于", pinyin: "guānyú",   meaning: "về, liên quan đến",            type: "giới từ",  example: "关于这件事。 - Về chuyện này." },
  { id: 315, hanzi: "只要", pinyin: "zhǐyào",   meaning: "chỉ cần, miễn là",            type: "liên từ",  example: "只要努力就行。 - Chỉ cần cố gắng là được." },
  { id: 316, hanzi: "里面", pinyin: "lǐmiàn",   meaning: "bên trong, trong",             type: "danh từ",  example: "里面有什么？ - Bên trong có gì?" },
  { id: 317, hanzi: "到底", pinyin: "dàodǐ",    meaning: "rốt cuộc, đến cùng",          type: "phó từ",   example: "到底怎么了？ - Rốt cuộc có chuyện gì?" },
  { id: 318, hanzi: "了解", pinyin: "liǎojiě",  meaning: "hiểu rõ, biết rõ",            type: "động từ",  example: "我了解你。 - Tôi hiểu rõ bạn." },
  { id: 319, hanzi: "结束", pinyin: "jiéshù",   meaning: "kết thúc, chấm dứt",          type: "động từ",  example: "电影结束了。 - Phim kết thúc rồi." },
  { id: 320, hanzi: "公司", pinyin: "gōngsī",   meaning: "công ty",                     type: "danh từ",  example: "我在公司工作。 - Tôi làm việc ở công ty." },
  { id: 321, hanzi: "成为", pinyin: "chéngwéi", meaning: "trở thành, biến thành",       type: "động từ",  example: "我想成为医生。 - Tôi muốn trở thành bác sĩ." },
  { id: 322, hanzi: "永远", pinyin: "yǒngyuǎn", meaning: "vĩnh viễn, mãi mãi",         type: "phó từ",   example: "我永远爱你。 - Anh yêu em mãi mãi." },
  { id: 323, hanzi: "帮助", pinyin: "bāngzhù",  meaning: "giúp đỡ, viện trợ",           type: "động từ",  example: "谢谢你的帮助。 - Cảm ơn sự giúp đỡ của bạn." },
  { id: 324, hanzi: "确定", pinyin: "quèdìng",  meaning: "xác định, khẳng định, chắc",  type: "động từ",  example: "你确定吗？ - Bạn chắc chắn không?" },
  { id: 325, hanzi: "有人", pinyin: "yǒurén",   meaning: "có người, ai đó",             type: "đại từ",   example: "有人叫你。 - Có người gọi bạn." },
  { id: 326, hanzi: "清楚", pinyin: "qīngchǔ",  meaning: "rõ ràng, tinh tường",         type: "tính từ",  example: "说清楚！ - Nói rõ ràng!" },
  { id: 327, hanzi: "安全", pinyin: "ānquán",   meaning: "an toàn",                     type: "tính từ",  example: "注意安全！ - Chú ý an toàn!" },
  { id: 328, hanzi: "回家", pinyin: "huí jiā",  meaning: "về nhà",                      type: "động từ",  example: "我回家了。 - Tôi về nhà rồi." },
  { id: 329, hanzi: "愿意", pinyin: "yuànyì",   meaning: "sẵn lòng, vui lòng",          type: "động từ",  example: "我愿意帮你。 - Tôi sẵn lòng giúp bạn." },
  { id: 330, hanzi: "计划", pinyin: "jìhuà",    meaning: "kế hoạch",                    type: "danh từ",  example: "你有什么计划？ - Bạn có kế hoạch gì?" },
  { id: 331, hanzi: "不能", pinyin: "bùnéng",   meaning: "không thể, không được",       type: "trợ động", example: "我不能去。 - Tôi không thể đi." },
  { id: 332, hanzi: "说话", pinyin: "shuōhuà",  meaning: "nói chuyện, trò chuyện",      type: "động từ",  example: "我们说话吧。 - Chúng ta nói chuyện đi." },
  { id: 333, hanzi: "有些", pinyin: "yǒuxiē",   meaning: "có một số, một ít",           type: "đại từ",   example: "有些人不喜欢。 - Một số người không thích." },
  { id: 334, hanzi: "感谢", pinyin: "gǎnxiè",   meaning: "cảm ơn, cảm tạ",             type: "động từ",  example: "非常感谢！ - Cảm ơn rất nhiều!" },
  { id: 335, hanzi: "以后", pinyin: "yǐhòu",    meaning: "sau này, về sau",             type: "thời gian",example: "以后再说。 - Để sau nói." },
  { id: 336, hanzi: "照片", pinyin: "zhàopiàn", meaning: "bức ảnh, hình ảnh",           type: "danh từ",  example: "拍照片。 - Chụp ảnh." },
  { id: 337, hanzi: "欢迎", pinyin: "huānyíng", meaning: "chào mừng, hoan nghênh",      type: "động từ",  example: "欢迎来到！ - Chào mừng đến!" },
  { id: 338, hanzi: "兄弟", pinyin: "xiōngdì",  meaning: "anh em, huynh đệ",            type: "danh từ",  example: "我们是兄弟。 - Chúng tôi là anh em." },
  { id: 339, hanzi: "从来", pinyin: "cónglái",  meaning: "từ trước đến nay, chưa hề",   type: "phó từ",   example: "我从来不说谎。 - Tôi chưa bao giờ nói dối." },
  { id: 340, hanzi: "总是", pinyin: "zǒng shì", meaning: "luôn luôn, lúc nào cũng",     type: "phó từ",   example: "他总是迟到。 - Anh ấy luôn luôn đến trễ." },
  { id: 341, hanzi: "小姐", pinyin: "xiǎojiě",  meaning: "cô, tiểu thư",               type: "danh từ",  example: "这位小姐。 - Cô ấy." },
  { id: 342, hanzi: "消息", pinyin: "xiāoxī",   meaning: "tin tức, thông tin",           type: "danh từ",  example: "有什么消息？ - Có tin tức gì không?" },
  { id: 343, hanzi: "如此", pinyin: "rúcǐ",     meaning: "như vậy, như thế",             type: "đại từ",   example: "事情如此简单。 - Sự việc đơn giản như vậy." },
  { id: 344, hanzi: "无法", pinyin: "wúfǎ",     meaning: "không thể, không có cách",     type: "phó từ",   example: "我无法理解。 - Tôi không thể hiểu." },
  { id: 345, hanzi: "房子", pinyin: "fángzi",   meaning: "ngôi nhà",                     type: "danh từ",  example: "这是我的房子。 - Đây là nhà của tôi." },

  // 201-300 trong danh sách
  { id: 346, hanzi: "听说", pinyin: "tīng shuō",meaning: "nghe nói",                    type: "động từ",  example: "听说你要结婚了。 - Nghe nói bạn sắp kết hôn." },
  { id: 347, hanzi: "参加", pinyin: "cānjiā",   meaning: "tham gia, tham dự",            type: "động từ",  example: "参加比赛。 - Tham gia thi đấu." },
  { id: 348, hanzi: "办法", pinyin: "bànfǎ",    meaning: "cách, biện pháp",              type: "danh từ",  example: "有办法。 - Có cách." },
  { id: 349, hanzi: "唯一", pinyin: "wéiyī",    meaning: "duy nhất",                     type: "tính từ",  example: "他是唯一的。 - Anh ấy là duy nhất." },
  { id: 350, hanzi: "回去", pinyin: "huíqù",    meaning: "trở về, đi về",                type: "động từ",  example: "我要回去了。 - Tôi phải về rồi." },
  { id: 351, hanzi: "人们", pinyin: "rénmen",   meaning: "mọi người, người ta",           type: "đại từ",   example: "人们都很好。 - Mọi người đều tốt." },
  { id: 352, hanzi: "选择", pinyin: "xuǎnzé",   meaning: "lựa chọn",                     type: "động từ",  example: "请做出选择。 - Hãy đưa ra lựa chọn." },
  { id: 353, hanzi: "原因", pinyin: "yuányīn",  meaning: "nguyên nhân, lý do",           type: "danh từ",  example: "原因是什么？ - Nguyên nhân là gì?" },
  { id: 354, hanzi: "接受", pinyin: "jiēshòu",  meaning: "tiếp nhận, chấp nhận",          type: "động từ",  example: "接受现实。 - Chấp nhận thực tế." },
  { id: 355, hanzi: "改变", pinyin: "gǎibiàn",  meaning: "thay đổi",                     type: "động từ",  example: "改变生活。 - Thay đổi cuộc sống." },
  { id: 356, hanzi: "出现", pinyin: "chūxiàn",  meaning: "xuất hiện, hiện ra",            type: "động từ",  example: "问题出现了。 - Vấn đề đã xuất hiện." },
  { id: 357, hanzi: "打算", pinyin: "dǎsuàn",   meaning: "dự định, dự kiến",              type: "động từ",  example: "你打算去哪儿？ - Bạn dự định đi đâu?" },
  { id: 358, hanzi: "特别", pinyin: "tèbié",    meaning: "đặc biệt, rất",                type: "tính từ",  example: "这很特别。 - Cái này rất đặc biệt." },
  { id: 359, hanzi: "注意", pinyin: "zhùyì",    meaning: "chú ý, để ý",                  type: "động từ",  example: "请注意！ - Hãy chú ý!" },
  { id: 360, hanzi: "结果", pinyin: "jiéguǒ",   meaning: "kết quả",                      type: "danh từ",  example: "结果如何？ - Kết quả thế nào?" },
  { id: 361, hanzi: "其实", pinyin: "qíshí",    meaning: "kỳ thực, thực ra",             type: "phó từ",   example: "其实很简单。 - Thực ra rất đơn giản." },
  { id: 362, hanzi: "小心", pinyin: "xiǎoxīn",  meaning: "cẩn thận",                     type: "tính từ",  example: "小心点！ - Cẩn thận!" },
  { id: 363, hanzi: "只有", pinyin: "zhǐyǒu",   meaning: "chỉ có",                       type: "phó từ",   example: "只有我知道。 - Chỉ có tôi biết." },
  { id: 364, hanzi: "绝对", pinyin: "juéduì",   meaning: "tuyệt đối",                    type: "phó từ",   example: "绝对不行！ - Tuyệt đối không được!" },
  { id: 365, hanzi: "进去", pinyin: "jìnqù",    meaning: "đi vào, bước vào",             type: "động từ",  example: "请进去。 - Hãy vào trong đi." },
  { id: 366, hanzi: "至少", pinyin: "zhìshǎo",  meaning: "ít nhất",                      type: "phó từ",   example: "至少三个。 - Ít nhất ba cái." },
  { id: 367, hanzi: "整个", pinyin: "zhěnggè",  meaning: "toàn bộ, cả",                  type: "đại từ",   example: "整个城市。 - Toàn bộ thành phố." },
  { id: 368, hanzi: "听到", pinyin: "tīng dào", meaning: "nghe được, nghe thấy",          type: "động từ",  example: "我听到了。 - Tôi nghe thấy rồi." },
  { id: 369, hanzi: "正在", pinyin: "zhèngzài", meaning: "đang (làm gì đó)",             type: "phó từ",   example: "我正在吃饭。 - Tôi đang ăn cơm." },
  { id: 370, hanzi: "感到", pinyin: "gǎndào",   meaning: "cảm thấy",                     type: "động từ",  example: "感到很幸福。 - Cảm thấy rất hạnh phúc." },
  { id: 371, hanzi: "故事", pinyin: "gùshì",    meaning: "câu chuyện",                   type: "danh từ",  example: "讲故事。 - Kể chuyện." },
  { id: 372, hanzi: "结婚", pinyin: "jiéhūn",   meaning: "kết hôn",                      type: "động từ",  example: "他们结婚了。 - Họ đã kết hôn." },
  { id: 373, hanzi: "妻子", pinyin: "qīzi",     meaning: "vợ",                           type: "danh từ",  example: "我的妻子。 - Vợ của tôi." },
  { id: 374, hanzi: "努力", pinyin: "nǔ lì",    meaning: "nỗ lực, cố gắng",             type: "động từ",  example: "要努力学习！ - Phải cố gắng học!" },
  { id: 375, hanzi: "害怕", pinyin: "hàipà",    meaning: "sợ hãi, sợ",                  type: "động từ",  example: "我害怕。 - Tôi sợ." },
  { id: 376, hanzi: "成功", pinyin: "chénggōng",meaning: "thành công",                   type: "động từ",  example: "祝你成功！ - Chúc bạn thành công!" },
  { id: 377, hanzi: "开心", pinyin: "kāixīn",   meaning: "vui vẻ, vui mừng",             type: "tính từ",  example: "我很开心。 - Tôi rất vui." },
  { id: 378, hanzi: "母亲", pinyin: "mǔqīn",    meaning: "mẹ, mẫu thân (trang trọng)",  type: "danh từ",  example: "我的母亲很善良。 - Mẹ tôi rất tốt bụng." },
  { id: 379, hanzi: "丈夫", pinyin: "zhàngfū",  meaning: "chồng",                        type: "danh từ",  example: "我的丈夫。 - Chồng của tôi." },
  { id: 380, hanzi: "解决", pinyin: "jiějué",   meaning: "giải quyết",                   type: "động từ",  example: "解决问题。 - Giải quyết vấn đề." },
  { id: 381, hanzi: "同意", pinyin: "tóngyì",   meaning: "đồng ý",                       type: "động từ",  example: "我同意你的意见。 - Tôi đồng ý với ý kiến của bạn." },
  { id: 382, hanzi: "帮忙", pinyin: "bāngmáng", meaning: "giúp đỡ",                      type: "động từ",  example: "请帮我忙。 - Xin hãy giúp tôi." },
  { id: 383, hanzi: "危险", pinyin: "wéixiǎn",  meaning: "nguy hiểm",                    type: "tính từ",  example: "这很危险！ - Cái này rất nguy hiểm!" },
  { id: 384, hanzi: "外面", pinyin: "wàimiàn",  meaning: "bên ngoài, phía ngoài",        type: "danh từ",  example: "在外面等。 - Đợi ở ngoài." },
  { id: 385, hanzi: "国家", pinyin: "guójiā",   meaning: "đất nước, quốc gia",           type: "danh từ",  example: "我爱我的国家。 - Tôi yêu đất nước tôi." },
  { id: 386, hanzi: "最近", pinyin: "zuìjìn",   meaning: "gần đây, dạo này",             type: "thời gian",example: "最近你好吗？ - Dạo này bạn khỏe không?" },
  { id: 387, hanzi: "声音", pinyin: "shēngyīn", meaning: "âm thanh, tiếng động",         type: "danh từ",  example: "声音太大了。 - Âm thanh quá lớn." },

  // 301-400 trong danh sách
  { id: 388, hanzi: "快乐", pinyin: "kuàilè",   meaning: "vui vẻ, hạnh phúc",           type: "tính từ",  example: "祝你快乐！ - Chúc bạn vui vẻ!" },
  { id: 389, hanzi: "可爱", pinyin: "kě'ài",    meaning: "đáng yêu, dễ thương",         type: "tính từ",  example: "真可爱！ - Thật dễ thương!" },
  { id: 390, hanzi: "完成", pinyin: "wánchéng", meaning: "hoàn thành",                   type: "động từ",  example: "完成任务。 - Hoàn thành nhiệm vụ." },
  { id: 391, hanzi: "上面", pinyin: "shàngmiàn",meaning: "bên trên, phía trên",           type: "danh từ",  example: "上面有什么？ - Bên trên có gì?" },
  { id: 392, hanzi: "有趣", pinyin: "yǒuqù",    meaning: "thú vị, hay",                  type: "tính từ",  example: "这本书很有趣。 - Quyển sách này rất thú vị." },
  { id: 393, hanzi: "真的", pinyin: "zhēn de",  meaning: "thật sự, thật mà",             type: "phó từ",   example: "真的！ - Thật sự!" },
  { id: 394, hanzi: "要求", pinyin: "yāoqiú",   meaning: "yêu cầu, đòi hỏi",             type: "động từ",  example: "有什么要求？ - Có yêu cầu gì không?" },
  { id: 395, hanzi: "除了", pinyin: "chúle",    meaning: "ngoài ra, trừ ra",             type: "giới từ",  example: "除了我，都来了。 - Ngoài tôi ra, mọi người đều đến." },
  { id: 396, hanzi: "虽然", pinyin: "suīrán",   meaning: "mặc dù, tuy nhiên",            type: "liên từ",  example: "虽然累，但是很快乐。 - Mặc dù mệt nhưng rất vui." },
  { id: 397, hanzi: "简单", pinyin: "jiǎndān",  meaning: "đơn giản",                     type: "tính từ",  example: "很简单！ - Rất đơn giản!" },
  { id: 398, hanzi: "不同", pinyin: "bùtóng",   meaning: "không giống, khác nhau",       type: "tính từ",  example: "我们不同。 - Chúng ta khác nhau." },
  { id: 399, hanzi: "家庭", pinyin: "jiātíng",  meaning: "gia đình",                     type: "danh từ",  example: "幸福的家庭。 - Gia đình hạnh phúc." },
  { id: 400, hanzi: "秘密", pinyin: "mìmì",     meaning: "bí mật",                       type: "danh từ",  example: "这是秘密。 - Đây là bí mật." },

  { id: 401, hanzi: "打开", pinyin: "dǎkāi",    meaning: "mở ra",                        type: "động từ",  example: "打开门。 - Mở cửa ra." },
  { id: 402, hanzi: "早上", pinyin: "zǎoshang", meaning: "buổi sáng sớm",               type: "thời gian",example: "早上好！ - Chào buổi sáng!" },
  { id: 403, hanzi: "任务", pinyin: "rènwù",    meaning: "nhiệm vụ",                     type: "danh từ",  example: "完成任务。 - Hoàn thành nhiệm vụ." },
  { id: 404, hanzi: "紧张", pinyin: "jǐnzhāng", meaning: "lo lắng, hồi hộp",             type: "tính từ",  example: "我很紧张。 - Tôi rất hồi hộp." },
  { id: 405, hanzi: "放弃", pinyin: "fàngqì",   meaning: "từ bỏ, bỏ cuộc",              type: "động từ",  example: "不要放弃！ - Đừng bỏ cuộc!" },
  { id: 406, hanzi: "大概", pinyin: "dàgài",    meaning: "khoảng, có lẽ, đại khái",      type: "phó từ",   example: "大概三点。 - Khoảng 3 giờ." },
  { id: 407, hanzi: "身体", pinyin: "shēntǐ",   meaning: "thân thể, cơ thể, sức khỏe",  type: "danh từ",  example: "身体健康。 - Sức khỏe tốt." },
  { id: 408, hanzi: "方式", pinyin: "fāngshì",  meaning: "phương thức, cách thức",       type: "danh từ",  example: "用这种方式。 - Dùng cách này." },
  { id: 409, hanzi: "重新", pinyin: "chóngxīn", meaning: "làm lại từ đầu, lại lần nữa", type: "phó từ",   example: "重新开始。 - Bắt đầu lại từ đầu." },
  { id: 410, hanzi: "想法", pinyin: "xiǎngfǎ",  meaning: "ý nghĩ, suy nghĩ, cách nghĩ", type: "danh từ",  example: "你的想法很好。 - Suy nghĩ của bạn rất tốt." },
  { id: 411, hanzi: "家里", pinyin: "jiālǐ",    meaning: "trong nhà, ở nhà",             type: "danh từ",  example: "家里有人吗？ - Trong nhà có ai không?" },
  { id: 412, hanzi: "带来", pinyin: "dài lái",  meaning: "đem lại, mang lại",             type: "động từ",  example: "带来好消息。 - Mang lại tin tốt." },
  { id: 413, hanzi: "大学", pinyin: "dàxué",    meaning: "đại học",                      type: "danh từ",  example: "上大学。 - Vào đại học." },
  { id: 414, hanzi: "照顾", pinyin: "zhàogù",   meaning: "chăm sóc",                     type: "động từ",  example: "照顾好自己。 - Hãy chăm sóc bản thân." },
  { id: 415, hanzi: "太太", pinyin: "tàitai",   meaning: "bà xã, vợ",                   type: "danh từ",  example: "我的太太。 - Vợ tôi." },
  { id: 416, hanzi: "聪明", pinyin: "cōngmíng", meaning: "thông minh",                   type: "tính từ",  example: "她很聪明。 - Cô ấy rất thông minh." },
  { id: 417, hanzi: "加油", pinyin: "jiāyóu",   meaning: "cố lên! cố gắng lên!",        type: "cảm thán", example: "加油！ - Cố lên!" },
  { id: 418, hanzi: "突然", pinyin: "túrán",    meaning: "đột nhiên, bất chợt",          type: "phó từ",   example: "突然下雨了。 - Đột nhiên trời mưa." },
  { id: 419, hanzi: "正常", pinyin: "zhèngcháng",meaning: "bình thường, thông thường",   type: "tính từ",  example: "这很正常。 - Cái này rất bình thường." },
  { id: 420, hanzi: "终于", pinyin: "zhōngyú",  meaning: "cuối cùng, rốt cuộc",          type: "phó từ",   example: "终于来了！ - Cuối cùng đến rồi!" },
  { id: 421, hanzi: "咖啡", pinyin: "kāfēi",    meaning: "cà phê",                       type: "danh từ",  example: "喝咖啡。 - Uống cà phê." },
  { id: 422, hanzi: "冷静", pinyin: "lěngjìng", meaning: "bình tĩnh, điềm tĩnh",        type: "tính từ",  example: "请冷静！ - Hãy bình tĩnh!" },
  { id: 423, hanzi: "方法", pinyin: "fāngfǎ",   meaning: "phương pháp, cách làm",        type: "danh từ",  example: "有好的方法。 - Có phương pháp tốt." },
  { id: 424, hanzi: "能力", pinyin: "nénglì",   meaning: "năng lực, khả năng",           type: "danh từ",  example: "你的能力很强。 - Năng lực của bạn rất mạnh." },
  { id: 425, hanzi: "完美", pinyin: "wánměi",   meaning: "hoàn hảo",                     type: "tính từ",  example: "这很完美！ - Cái này hoàn hảo!" },
  { id: 426, hanzi: "目标", pinyin: "mùbiāo",   meaning: "mục tiêu",                     type: "danh từ",  example: "你的目标是什么？ - Mục tiêu của bạn là gì?" },
  { id: 427, hanzi: "精神", pinyin: "jīngshén", meaning: "tinh thần",                    type: "danh từ",  example: "精神很好。 - Tinh thần rất tốt." },

  // 401-500 trong danh sách
  { id: 428, hanzi: "另外", pinyin: "lìngwài",  meaning: "ngoài ra",                     type: "liên từ",  example: "另外，我还有问题。 - Ngoài ra, tôi còn có câu hỏi." },
  { id: 429, hanzi: "休息", pinyin: "xiūxi",    meaning: "nghỉ ngơi",                    type: "động từ",  example: "我要休息了。 - Tôi phải nghỉ rồi." },
  { id: 430, hanzi: "每天", pinyin: "měitiān",  meaning: "mỗi ngày, hằng ngày",          type: "thời gian",example: "我每天学习。 - Tôi học mỗi ngày." },
  { id: 431, hanzi: "回答", pinyin: "huídá",    meaning: "trả lời, giải đáp",             type: "động từ",  example: "请回答问题。 - Hãy trả lời câu hỏi." },
  { id: 432, hanzi: "负责", pinyin: "fùzé",     meaning: "chịu trách nhiệm",             type: "động từ",  example: "你要负责！ - Bạn phải chịu trách nhiệm!" },
  { id: 433, hanzi: "关心", pinyin: "guānxīn",  meaning: "quan tâm, lo lắng cho",        type: "động từ",  example: "我很关心你。 - Tôi rất quan tâm bạn." },
  { id: 434, hanzi: "兴趣", pinyin: "xìngqù",   meaning: "hứng thú, sở thích",           type: "danh từ",  example: "你有什么兴趣？ - Bạn có sở thích gì?" },
  { id: 435, hanzi: "经历", pinyin: "jīnglì",   meaning: "trải qua, kinh nghiệm",        type: "động từ",  example: "丰富的经历。 - Kinh nghiệm phong phú." },
  { id: 436, hanzi: "不用", pinyin: "bùyòng",   meaning: "không cần, khỏi cần",          type: "phó từ",   example: "不用谢！ - Không cần cảm ơn!" },
  { id: 437, hanzi: "人类", pinyin: "rénlèi",   meaning: "loài người, nhân loại",         type: "danh từ",  example: "人类很伟大。 - Loài người thật vĩ đại." },
  { id: 438, hanzi: "自由", pinyin: "zìyóu",    meaning: "tự do",                        type: "tính từ",  example: "我想自由。 - Tôi muốn tự do." },
  { id: 439, hanzi: "支持", pinyin: "zhīchí",   meaning: "ủng hộ, hỗ trợ",              type: "động từ",  example: "我支持你！ - Tôi ủng hộ bạn!" },
  { id: 440, hanzi: "生气", pinyin: "shēngqì",  meaning: "tức giận, nóng giận",          type: "động từ",  example: "别生气！ - Đừng tức giận!" },
  { id: 441, hanzi: "建议", pinyin: "jiànyì",   meaning: "kiến nghị, đề xuất",           type: "động từ",  example: "你有什么建议？ - Bạn có đề xuất gì?" },
  { id: 442, hanzi: "生日", pinyin: "shēngrì",  meaning: "sinh nhật",                    type: "danh từ",  example: "生日快乐！ - Chúc mừng sinh nhật!" },
  { id: 443, hanzi: "晚安", pinyin: "wǎn'ān",   meaning: "ngủ ngon, chúc ngủ ngon",      type: "chào hỏi",example: "晚安！ - Chúc ngủ ngon!" },
  { id: 444, hanzi: "年轻", pinyin: "niánqīng", meaning: "trẻ, tuổi trẻ",               type: "tính từ",  example: "他很年轻。 - Anh ấy rất trẻ." },
  { id: 445, hanzi: "下面", pinyin: "xiàmiàn",  meaning: "phía dưới, bên dưới",          type: "danh từ",  example: "下面是什么？ - Bên dưới là gì?" },
  { id: 446, hanzi: "钥匙", pinyin: "yàoshi",   meaning: "chìa khóa",                    type: "danh từ",  example: "你拿着钥匙吗？ - Bạn có chìa khóa không?" },
  { id: 447, hanzi: "哥哥", pinyin: "gēgē",     meaning: "anh trai",                     type: "danh từ",  example: "我的哥哥。 - Anh trai tôi." },
  { id: 448, hanzi: "必要", pinyin: "bìyào",    meaning: "cần thiết, thiết yếu",         type: "tính từ",  example: "这是必要的。 - Điều này cần thiết." },
  { id: 449, hanzi: "手机", pinyin: "shǒujī",   meaning: "điện thoại di động",            type: "danh từ",  example: "我的手机呢？ - Điện thoại của tôi đâu?" },
  { id: 450, hanzi: "忘记", pinyin: "wàngjì",   meaning: "quên",                         type: "động từ",  example: "我忘记了。 - Tôi quên rồi." },
  { id: 451, hanzi: "首先", pinyin: "shǒuxiān", meaning: "đầu tiên, trước hết",          type: "phó từ",   example: "首先介绍一下。 - Trước hết giới thiệu một chút." },
  { id: 452, hanzi: "个人", pinyin: "gèrén",    meaning: "cá nhân, riêng tư",            type: "danh từ",  example: "个人意见。 - Ý kiến cá nhân." },
  { id: 453, hanzi: "坚持", pinyin: "jiānchí",  meaning: "kiên trì, kiên định",          type: "động từ",  example: "坚持就是胜利。 - Kiên trì là chiến thắng." },
  { id: 454, hanzi: "意义", pinyin: "yìyì",     meaning: "ý nghĩa",                      type: "danh từ",  example: "这有意义吗？ - Cái này có ý nghĩa không?" },
  { id: 455, hanzi: "承认", pinyin: "chéngrèn", meaning: "thừa nhận, công nhận",         type: "động từ",  example: "我承认错了。 - Tôi thừa nhận đã sai." },
  { id: 456, hanzi: "理由", pinyin: "lǐyóu",    meaning: "lý do",                        type: "danh từ",  example: "你有什么理由？ - Bạn có lý do gì?" },
  { id: 457, hanzi: "政府", pinyin: "zhèngfǔ",  meaning: "chính phủ",                    type: "danh từ",  example: "政府的决定。 - Quyết định của chính phủ." },
  { id: 458, hanzi: "生意", pinyin: "shēngyì",  meaning: "kinh doanh, buôn bán",         type: "danh từ",  example: "做生意。 - Kinh doanh." },
  { id: 459, hanzi: "记住", pinyin: "jì zhù",   meaning: "ghi nhớ, nhớ kỹ",             type: "động từ",  example: "记住我的话！ - Hãy nhớ lời tôi!" },
  { id: 460, hanzi: "幸运", pinyin: "xìngyùn",  meaning: "may mắn, vận may",             type: "tính từ",  example: "我很幸运。 - Tôi rất may mắn." },
  { id: 461, hanzi: "未来", pinyin: "wèilái",   meaning: "tương lai",                    type: "danh từ",  example: "美好的未来。 - Tương lai tươi sáng." },
  { id: 462, hanzi: "可怜", pinyin: "kělián",   meaning: "đáng thương, tội nghiệp",      type: "tính từ",  example: "真可怜！ - Thật đáng thương!" },
  { id: 463, hanzi: "加入", pinyin: "jiārù",    meaning: "gia nhập, tham gia",            type: "động từ",  example: "加入我们吧！ - Hãy gia nhập chúng tôi!" },
  { id: 464, hanzi: "治疗", pinyin: "zhìliáo",  meaning: "chữa trị, điều trị",           type: "động từ",  example: "接受治疗。 - Tiếp nhận điều trị." },
  { id: 465, hanzi: "原谅", pinyin: "yuánliàng",meaning: "tha thứ, bỏ qua",              type: "động từ",  example: "请原谅我！ - Hãy tha thứ cho tôi!" },
  { id: 466, hanzi: "比较", pinyin: "bǐjiào",   meaning: "tương đối, khá",               type: "phó từ",   example: "比较好。 - Tương đối tốt." },
  { id: 467, hanzi: "弟弟", pinyin: "dìdì",     meaning: "em trai",                      type: "danh từ",  example: "我的弟弟。 - Em trai tôi." },
  { id: 468, hanzi: "新闻", pinyin: "xīnwén",   meaning: "tin tức, thời sự",             type: "danh từ",  example: "看新闻。 - Xem tin tức." },
  { id: 469, hanzi: "跳舞", pinyin: "tiàowǔ",   meaning: "nhảy múa",                     type: "động từ",  example: "我喜欢跳舞。 - Tôi thích nhảy múa." },
  { id: 470, hanzi: "信任", pinyin: "xìnrèn",   meaning: "tin tưởng, tín nhiệm",         type: "động từ",  example: "我信任你。 - Tôi tin tưởng bạn." },
  { id: 471, hanzi: "道歉", pinyin: "dàoqiàn",  meaning: "xin lỗi, nhận lỗi",            type: "động từ",  example: "向他道歉。 - Xin lỗi anh ấy." },
  { id: 472, hanzi: "存在", pinyin: "cúnzài",   meaning: "tồn tại",                      type: "động từ",  example: "还存在吗？ - Còn tồn tại không?" },
  { id: 473, hanzi: "婚礼", pinyin: "hūnlǐ",    meaning: "đám cưới, hôn lễ",             type: "danh từ",  example: "参加婚礼。 - Tham dự đám cưới." },
  { id: 474, hanzi: "组织", pinyin: "zǔzhī",    meaning: "tổ chức",                      type: "động từ",  example: "组织活动。 - Tổ chức hoạt động." },
];

let savedHSK1 = JSON.parse(localStorage.getItem('nhim_hsk1'));
let HSK1_VOCABULARY = savedHSK1 || _default_HSK1_VOCABULARY;

// Tự động bổ sung các từ mới được code vào nhưng chưa có trong localStorage (dành cho update)
if (savedHSK1) {
    const existingIds = new Set(savedHSK1.map(w => w.id));
    const missingItems = _default_HSK1_VOCABULARY.filter(w => !existingIds.has(w.id));
    if (missingItems.length > 0) {
        HSK1_VOCABULARY = [...savedHSK1, ...missingItems];
        localStorage.setItem('nhim_hsk1', JSON.stringify(HSK1_VOCABULARY));
    }
}

// Export for use in other modules
if (typeof module !== 'undefined') module.exports = HSK1_VOCABULARY;
